name: watson
title: Watson time tracker
base: core18
version: '1.10.0-snap1'
license: MIT
summary: CLI-based time tracking/logging application with local or cloud storage. 

description: | 
        Watson is here to help you monitor your time. You want to know how much time you are spending on your projects? You want to generate a nice report for your client? Watson is here for you.
        
        Please note: This unofficial snap package of Watson is NOT maintained by the Watson developers themselves. Please see the "contact" information in "snap info watson-tracker" for snap packaging-related questions or support. 
icon: gui/logo-watson-square-256.png

grade: stable
confinement: strict 

apps:
        watson:
                command: bin/watson

parts:
  watson:
    plugin: python
    python-packages: ['td-watson']
    python-version: python3
